<a href="https://colab.research.google.com/github/FelipeArgona/AnaliseDeDadosPandasArgona/blob/main/Analise_de_Dados_com_Pandas_Combustiveis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aula de verÃ£o Analise de dados com Pandas

In [40]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [41]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [42]:
#import da biblioteca e carregamento do data frame

import pandas as pd

comb_df = pd.read_excel("/content/drive/MyDrive/ca-NOV-2021-02.xlsx")

In [43]:
#ver o data frame

print(comb_df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [44]:
display(comb_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

In [45]:
#shape e describe

print(comb_df.shape)

print(comb_df.describe())

(168409, 16)
       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [46]:
#head

display(comb_df.head(5))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA

In [47]:
print(comb_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB
None

In [48]:
#Aqui criamos um novo dataframe apenas com as colunas desejadas 
ca_df = comb_df[['Revenda','Municipio','Produto','Valor de Venda']]
display(ca_df)

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799
1,POSTO ARAPIRACA LTDA,ARAPIRACA,ETANOL,5.299
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,5.549
3,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA ADITIVADA,6.899
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,5.649
...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580

In [49]:
#Locaizando preÃ§os de etanol em INDAITUBA
# Sort

etanol_inda_df = ca_df.loc[(ca_df['Produto'] == 'ETANOL') & (ca_df ['Municipio']== 'INDAIATUBA')]
etanol_inda_df.sort_values(by='Valor de Venda', inplace = True)
display(etanol_inda_df)

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,Revenda,Municipio,Produto,Valor de Venda
160592,AUTO POSTO NAMORADA II LTDA.,INDAIATUBA,ETANOL,4.679
140194,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,INDAIATUBA,ETANOL,4.679
140661,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,INDAIATUBA,ETANOL,4.699
159497,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,INDAIATUBA,ETANOL,4.699
141167,AUTO POSTO ESPLANADA DE INDAIA LTDA,INDAIATUBA,ETANOL,4.699
...,...,...,...,...
51129,AUTO POSTO CIDADE DO SOL II LTDA,INDAIATUBA,ETANOL,5.599
51138,AUTO POSTO NAMORADA II LTDA.,INDAIATUBA,ETANOL,5.599
84395,AUTO POSTO NAMORADA II LTDA.,INDAIATUBA,ETANOL,5.599
65878,AUTO POSTO CIDADE DO SOL II LTDA,INDAIATUBA,ETANOL,5.599
65363,AUTO POSTO INDIANA SELF LTDA.,INDAIATUBA,ETANOL,6.197

In [50]:
#Qual a media de preÃ§os dos combustiveis gasolina e gasolina aditivada do bairro Bela vista em sÃ£o paulo
#funcao isin

#comb_sp = comb_df.loc[(comb_df['Bairro'] == 'MOOCA') & (comb_df['Municipio'] == 'SAO PAULO') & ((comb_df['Produto'] == 'GASOLINA') | (comb_df['Produto'] == 'GASOLINA ADITIVADA'))]

comb_sp = comb_df.loc[(comb_df['Bairro'] == 'MOOCA') & 
                      (comb_df['Municipio'] == 'SAO PAULO') & 
                      (comb_df['Produto'].isin(['GASOLINA', 'GASOLINA ADITIVADA']))]

comb_sp = comb_sp [['Revenda','Municipio','Bairro','Produto','Valor de Venda']]
comb_sp.sort_values(by='Valor de Venda', inplace = True)
display(comb_sp.mean())
display(comb_sp)

<ipython-input-50-63819fd9246f>:12: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  display(comb_sp.mean())

Valor de Venda    6.575596
dtype: float64

,Revenda,Municipio,Bairro,Produto,Valor de Venda
11590,AUTO POSTO LIK LTDA,SAO PAULO,MOOCA,GASOLINA,5.999
139297,AUTO POSTO PANTERA LTDA,SAO PAULO,MOOCA,GASOLINA,5.999
11648,AUTO POSTO PANTERA LTDA,SAO PAULO,MOOCA,GASOLINA,6.099
103242,NOVO BRILHO CENTRO AUTOMOTIVO LTDA,SAO PAULO,MOOCA,GASOLINA,6.199
66374,NOVO BRILHO CENTRO AUTOMOTIVO LTDA,SAO PAULO,MOOCA,GASOLINA,6.199
142001,NOVO BRILHO CENTRO AUTOMOTIVO LTDA,SAO PAULO,MOOCA,GASOLINA,6.199
11646,AUTO POSTO PANTERA LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.199
139332,POSTO DE SERVICOS PARQUE DA MOOCA LTDA,SAO PAULO,MOOCA,GASOLINA,6.299
100341,AUTO POSTO PANTERA LTDA,SAO PAULO,MOOCA,GASOLINA,6.299
139295,AUTO POSTO PANTERA LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.299
63300,AUTO POSTO PANTERA LTDA,SAO PAULO,MOOCA,GASOLINA,6.299
13344,POSTO DE SERVICOS NOVA MOOCA LTDA.,SAO PAULO,MOOCA,GASOLINA,6.399
100372,POSTO DE SERVICOS PARQUE DA MOOCA LTDA,SAO PAULO,MOOCA,GASOLINA,6.399
63365,POSTO DE SERVICOS PARQUE DA MOOCA LTDA,SAO PAULO,MOOCA,GASOLINA,6.399
140720,POSTO DE SERVICOS NOVA MOOCA LTDA.,SAO PAULO,MOOCA,GASOLINA,6.499
63302,AUTO POSTO PANTERA LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.499
100339,AUTO POSTO PANTERA LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.499
13271,POSTO DE SERVICOS AUTOMOTIVOS E COMERCIO DE CO...,SAO PAULO,MOOCA,GASOLINA,6.499
101985,POSTO DE SERVICOS NOVA MOOCA LTDA.,SAO PAULO,MOOCA,GASOLINA,6.499
65113,POSTO DE SERVICOS NOVA MOOCA LTDA.,SAO PAULO,MOOCA,GASOLINA,6.499
13342,POSTO DE SERVICOS NOVA MOOCA LTDA.,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.599
139315,AUTO POSTO TEJO LTDA,SAO PAULO,MOOCA,GASOLINA,6.599
103555,CENTRO AUTOMOTIVO CENTER PAES DE BARROS LTDA,SAO PAULO,MOOCA,GASOLINA,6.599
139277,AUTO POSTO POINT LTDA,SAO PAULO,MOOCA,GASOLINA,6.599
100310,AUTO POSTO POINT LTDA,SAO PAULO,MOOCA,GASOLINA,6.599
13733,AUTO POSTO TRILHOS LTDA.,SAO PAULO,MOOCA,GASOLINA,6.599
63246,AUTO POSTO POINT LTDA,SAO PAULO,MOOCA,GASOLINA,6.599
11836,CENTRO AUTOMOTIVO SAO RAFAEL LTDA,SAO PAULO,MOOCA,GASOLINA,6.699
65115,POSTO DE SERVICOS NOVA MOOCA LTDA.,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.699
100359,AUTO POSTO TEJO LTDA,SAO PAULO,MOOCA,GASOLINA,6.699
140718,POSTO DE SERVICOS NOVA MOOCA LTDA.,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.699
101983,POSTO DE SERVICOS NOVA MOOCA LTDA.,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.699
63341,AUTO POSTO TEJO LTDA,SAO PAULO,MOOCA,GASOLINA,6.699
13730,AUTO POSTO TRILHOS LTDA.,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.799
139313,AUTO POSTO TEJO LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.799
63248,AUTO POSTO POINT LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.799
139275,AUTO POSTO POINT LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.799
100308,AUTO POSTO POINT LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.799
63343,AUTO POSTO TEJO LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.899
11834,CENTRO AUTOMOTIVO SAO RAFAEL LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.899
63345,AUTO POSTO PAES DE BARROS LTDA,SAO PAULO,MOOCA,GASOLINA,6.899
139318,AUTO POSTO PAES DE BARROS LTDA,SAO PAULO,MOOCA,GASOLINA,6.899
100362,AUTO POSTO PAES DE BARROS LTDA,SAO PAULO,MOOCA,GASOLINA,6.899
100357,AUTO POSTO TEJO LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.899
63347,AUTO POSTO PAES DE BARROS LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.999
139316,AUTO POSTO PAES DE BARROS LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.999
100360,AUTO POSTO PAES DE BARROS LTDA,SAO PAULO,MOOCA,GASOLINA ADITIVADA,6.999

In [51]:
from numpy import shape
shape(comb_sp)

(47, 5)

In [52]:
# Media de valor geral por tipo de combustivel
# Round para casas decimais

media_comb_df = ca_df[['Produto', 'Valor de Venda']].groupby(by='Produto').mean().round(2)
display(media_comb_df)

                    Valor de Venda
Produto
DIESEL                        5.38
DIESEL S10                    5.45
ETANOL                        5.46
GASOLINA                      6.71
GASOLINA ADITIVADA            6.86
GNV                           4.39

In [53]:
# Para adicionar uma coluna de valor booleano em nosso data frame
# Por default serÃ¡ true para todas as linhas

comb_df['Ativo'] = True
comb_df.shape
display(comb_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA,True
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA,True
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA,True
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA,True
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA,True
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA,True
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA,True
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA,True
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA,True

In [54]:
# Condicionando a coluna uma coluna 'OBS'
# que preencha "MINHA CIDADE" quando o Municipio for sao paulo

#comb_df['Obs'] = "MINHA CIDADE" is comb_df['MINICIPIO'] == 'SAO PAULO' else ""

In [55]:
#Exportar saÃ­da

comb_sp.to_excel('combustivel_sp.xlsx', sheet_name='Combustiveis em sao paulo')